name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:  # name of the job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.14
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
      -name: Build prod bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build:prod

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/sample-app:latest
